### ISSUE TITLE
handle  misaligned load/store

### ISSUE THREAD

**Issue by manageryzy** [kendryte/kendryte-freertos-sdk#12]
### Missing feature

handle misaligned load/store & report error message

### Justification

add handler for misaligned load/store

### Workarounds

no

**Comment by ly0** [comment]
SDK does handle misaligned load/store error (https://github.com/kendryte/kendryte-freertos-sdk/blob/develop/lib/bsp/except.c#L64), but only calls `printf` to display the exception message.  
Considering that misaligned load/store is cause by user (including compilers), we should raise it instead of a workaround.
